silent; code_execution_config; exit; version
microsoft/FLAML pull request #1179
Opened 2023-08-11 01:39 UTC by sonichi

## Why are these changes needed?

1. Support silent mode to hide unnecessary messages in chess and group chat. (experimental)
2. Support lookback for multiple messages in code_execution_config. (experimental) @LittleLittleCloud 
3. Support exit group chat when human input is "exit".
4. Bump version to 2.0.0.

## Related issue number

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/FLAML/. See https://microsoft.github.io/FLAML/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

2023-08-13 12:02 UTC, qingyun-wu reviewed
Did you compile and check if the doc pages on the website are good? If so, LGTM.

2023-08-13 19:31 UTC, sonichi commented
> Did you compile and check if the doc pages on the website are good? If so, LGTM.

Partially. I made more changes when I checked. But it'll be good to have a second eye on it.

2023-08-14 01:43 UTC, qingyun-wu approved these changes

2023-08-14 02:02 UTC, thinkall commented
Could you also help fix a few typos in `autogen_agentchat_RetrieveChat.ipynb`?

```
-    "FLAML requires `Python>=3.8`. To run this notebook example, please install flaml with the [mathchat] option.\n",
+    "FLAML requires `Python>=3.8`. To run this notebook example, please install flaml with the [retrievechat] option.\n",


-    "We start by initialzing the `RetrieveAssistantAgent` and `RetrieveUserProxyAgent`. The system message needs to be set to \"You are a help
ful assistant.\" for RetrieveAssistantAgent. The detailed instructions are given in the user message. Later we will use the `RetrieveUserProxyA
gent.generate_init_prompt` to combine the instructions and a math problem for an initial prompt to be sent to the LLM assistant."
+    "We start by initialzing the `RetrieveAssistantAgent` and `RetrieveUserProxyAgent`. The system message needs to be set to \"You are a help
ful assistant.\" for RetrieveAssistantAgent. The detailed instructions are given in the user message. Later we will use the `RetrieveUserProxyA
gent.generate_init_prompt` to combine the instructions and a retrieval augmented generation task for an initial prompt to be sent to the LLM as
sistant."
```

2023-08-14 02:49 UTC, thinkall requested changes
I tried to run `autogen_agentchat_RetrieveChat.ipynb`, it failed with silent=True.

2023-08-14 02:49 UTC, thinkall commented on notebook/autogen_agentchat_RetrieveChat.ipynb
`pip install flaml[retrievechat]~=2.0.0rc5` also needs to be updated.

2023-08-14 03:36 UTC, thinkall reviewed
I've fixed errors in retrieve chat. One more thing is that there is a function `_generate_math_reply` in `math_user_proxy_agent.py`, but I don't see it being called when running `autogen_agentchat_MathChat.ipynb`. If it will be called, looks like it should be updated to handle parameter `config`.

2023-08-14 04:32 UTC, sonichi commented
> I've fixed errors in retrieve chat. One more thing is that there is a function `_generate_math_reply` in `math_user_proxy_agent.py`, but I don't see it being called when running `autogen_agentchat_MathChat.ipynb`. If it will be called, looks like it should be updated to handle parameter `config`.

Thanks. I fixed that.

2023-08-14 05:11 UTC, thinkall approved these changes

2023-08-14 08:17 UTC, merged