checkpoint naming in nonray mode, fix ray mode, delete checkpoints in nonray mode
microsoft/FLAML pull request #293
Opened 2021-11-19 05:35 UTC by liususan091219

…ning test mode, delete all the checkpoints in non-ray mode

2021-11-19 19:54 UTC, sonichi reviewed
first round of review.

2021-11-19 19:54 UTC, sonichi commented on flaml/model.py
> +        metric = datasets.load_metric(default_metric_name)
move into "else"

2021-11-19 19:54 UTC, sonichi commented on flaml/model.py
> +            if isinstance(self._metric_name, str) else {
lint

2021-11-19 19:54 UTC, sonichi commented on flaml/nlp/huggingface/trainer.py
>          )
lint

2021-11-19 19:54 UTC, sonichi commented on flaml/nlp/huggingface/trainer.py
> +            ckpt_dir = os.path.join(self.args.output_dir, f"{PREFIX_CHECKPOINT_DIR}-{self.state.global_step}")
what's the difference between if and else?

2021-11-19 19:54 UTC, sonichi commented on test/nlp/tmp.py
> +import os
what's the purpose of this file?

2021-11-21 21:56 UTC, sonichi requested changes

2021-11-21 21:56 UTC, sonichi commented on flaml/model.py
> +        self.trial_id = str(uuid.uuid1().hex)[:8]
BaseEstimator doesn't need this. Move to TransformerEstimator

2021-11-21 21:56 UTC, sonichi commented on flaml/model.py
> +        )
move to self.config2params()

2021-11-21 21:56 UTC, sonichi commented on flaml/model.py
> +                    default_metric_name
Is the default metric lower the better? If not, need to use minus.

2021-11-21 21:56 UTC, sonichi commented on test/nlp/test_autohf_maxiter1.py
> +        return
Does this test require ray?

2021-11-21 21:56 UTC, sonichi commented on test/nlp/test_autohf_ray.py
> +import os
I suggest changing an existing test into use ray. Any drawback for that?

2021-11-22 01:15 UTC, sonichi requested changes
please link relevant issues.

2021-11-22 01:15 UTC, sonichi commented on flaml/model.py
> +                }
```suggestion
            multiplier = -1 if default_metric_mode == "max" else 1
            return {
                "val_loss": metric.compute(
                    predictions=predictions, references=labels
                )[default_metric_name] * multiplier
            }

```

2021-11-22 01:15 UTC, sonichi commented on flaml/model.py
> +            test_dataset = Dataset.from_pandas(X_test)
This doesn't look right.
line 592 and 594 should be inside _preprocess().
Make sure test_dataset is defined in all cases as it is needed in line 607.

2021-11-22 01:15 UTC, sonichi commented on flaml/model.py
>              test_dataset = Dataset.from_pandas(X_test)
same problem

2021-11-23 05:46 UTC, liususan091219 commented
Closes Issue #290 #291

2021-11-23 05:50 UTC, sonichi commented on flaml/automl.py
> +                        else [X[idx]]
why not
```suggestion
                        else self._transformer._str_columns[idx]: [X[idx]]
```

2021-11-23 06:04 UTC, sonichi approved these changes

2021-11-23 18:49 UTC, sonichi reviewed
remove 
NLP
---

.. autoclass:: flaml.nlp.HPOArgs
   :members:
   
from index.rst?

2021-11-23 19:26 UTC, merged