added "**kwargs" to "predict"
microsoft/FLAML pull request #641
Opened 2022-07-19 21:23 UTC by zzheng93

2022-07-19 23:34 UTC, sonichi reviewed
There are a few more places in this file to add `**kwargs` I believe. @liususan091219 could you review the PR and follow up since you introduced `**kwargs` in the `predict()` function?

2022-07-20 00:01 UTC, zzheng93 commented
> There are a few more places in this file to add `**kwargs` I believe. @liususan091219 could you review the PR and follow up since you introduced `**kwargs` in the `predict()` function?

Hi @sonichi @liususan091219 , I did see more places, but I wasn't sure if they needed to be corrected.

2022-07-20 20:05 UTC, zzheng93 commented
> > > There are a few more places in this file to add `**kwargs` I believe. @liususan091219 could you review the PR and follow up since you introduced `**kwargs` in the `predict()` function?
> > 
> > 
> > Hi @sonichi @liususan091219 , I did see more places, but I wasn't sure if they needed to be corrected.
> 
> Thanks for your help @zzheng93! Basically you need to add **kwargs to all the places of model.predict inside of the predict function inside model.py (simply control+F ".predict" and add the **kwargs).
> 
> Also, to fix the current pytest error, please change the .get in the following line to .pop:
> 
> `https://github.com/microsoft/FLAML/blob/09eaf0f1b5231bdbe3a1e93476f9b0494c77d9dc/flaml/model.py#L315`

Hi @liususan091219 , sure, I'll do it!

2022-07-26 18:09 UTC, liususan091219 requested changes

2022-07-26 18:09 UTC, liususan091219 commented on flaml/model.py
> +        predictions = new_trainer.predict(test_dataset, **pred_kwargs)
```suggestion
        predictions = new_trainer.predict(test_dataset)

```

2022-07-26 18:09 UTC, liususan091219 commented on flaml/model.py
> +            predictions = new_trainer.predict(test_dataset, **pred_kwargs)
```suggestion
            predictions = new_trainer.predict(test_dataset)

```

2022-07-26 18:09 UTC, liususan091219 commented on flaml/model.py
> +                test_dataset, **pred_kwargs,
```suggestion
                test_dataset,

```

2022-07-26 18:43 UTC, zzheng93 commented
Hi @liususan091219, I have just committed and merged. Let me know if it works. Thanks!

2022-07-26 19:58 UTC, liususan091219 approved these changes

2022-07-26 20:19 UTC, liususan091219 commented
> Hi @liususan091219, I have just committed and merged. Let me know if it works. Thanks!

Looks good. Thank you!

2022-07-26 20:19 UTC, merged