stratified group kfold splitter
microsoft/FLAML pull request #899
Opened 2023-01-27 17:13 UTC by sonichi

## Why are these changes needed?

Support StratifiedGroupKFold object as `split_type`.

## Related issue number

Closes #886 

## Checks

- [x] I've used [pre-commit](https://microsoft.github.io/FLAML/docs/Contribute#pre-commit) to lint the changes in this PR, or I've made sure [lint with flake8](https://github.com/microsoft/FLAML/blob/816a82a1155b4de4705b21a615ccdff67c6da379/.github/workflows/python-package.yml#L54-L59) output is two 0s.
- [ ] I've included any doc changes needed for https://microsoft.github.io/FLAML/. See https://microsoft.github.io/FLAML/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

2023-01-30 14:28 UTC, skzhang1 approved these changes

2023-01-31 16:27 UTC, knoam requested changes
Should the test exclude Catboost? See https://github.com/microsoft/FLAML/issues/304. You can provide an estimator list:
"estimator_list": ['lgbm', 'rf', 'xgboost', 'extra_tree', 'xgb_limitdepth', 'lrl1']`

2023-01-31 16:27 UTC, knoam commented on test/automl/test_split.py
> +    settings = {
Add estimator_list excluding catboost

2023-01-31 18:28 UTC, sonichi commented on test/automl/test_split.py
> +    settings = {
Done.

2023-02-02 14:13 UTC, jtongxin approved these changes

2023-02-05 23:26 UTC, merged